### PR TITLE
[+] MO : Added support for DisplayHomeTab and DisplayHomeTabContent at BlockManufacturer module.

### PR DESCRIPTION
**Pull request by guestisp**
[+] MO : Added support for DisplayHomeTab and DisplayHomeTabContent at BlockManufacturer module.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Sorry can you please make it on "dev" branch ?

Maybe you should consider including directly the tpl /themes/default-bootstrap/manufacturer-list.tpl

Then Its good to have the possibility to hook here them but you should consider not adding the hooks in the install method as this may be then affecting the default install, demo etc.

Regards

**Comment by guestisp** [comment]
Hi,
Thank for your answer, but I have some questions.
If I work on blockmanufacturer, how can I change the manufacturer-list.tpl?
How can I add the hooks without use the install method?

Thanks a lot
Regards

**Comment by gRoussac** [comment]
Hi,

Sorry I do not get your first point. I just wanted to try to save a new template. Like others modules from there which are including product-list.tpl for instance.

Well you can hook them in back office in Modules tabs. Like for instance blockadvertising module. It can be hooked on left and right, but install is only installing on left. By adding the function you leave the possibility to hook/move it.

Regards

**Comment by guestisp** [comment]
How can I bind a module to a specific hook (like `displayHomeTab`) if I can't use `registerHook` in `install` method for the module ? Any sample code ?

In `blockadvertising` you are still registering both hooks....

In BO we can't bind a module to an hook not referenced by `registerHook'......

**Comment by gRoussac** [comment]
Hi,

It is just choosing one column depending on template conf in 1.6, but it is not registring on both

look old version if you do not understand.

https://github.com/PrestaShop/PrestaShop-1.5/blob/master/modules/blockadvertising/blockadvertising.php#L87

https://github.com/PrestaShop/PrestaShop-1.5/blob/master/modules/blockadvertising/blockadvertising.php#L218

It is a possibility only, not forced on right on installation, there is no  code to show. You can hook in BO a module if the hookXXX function exists.

Regards

**Comment by guestisp** [comment]
Ok, but we need to hook to homeTab not to a column, hometab is always set.

**Comment by gRoussac** [comment]
It is just a hook like all others. You can hook in back office in positions tab.

Regards

**Comment by guestisp** [comment]
No, I can't If i don't call `registerHook' in install. BO is triggering an error telling that module can't be bound to the hook.

Try to bind blockadvertise to a different hook....

**Comment by gRoussac** [comment]
Sorry but you can hook blockadvertising on right column as soon as hookRightColumn function exists.

Best regards

**Comment by guestisp** [comment]
So, we just have to create the function without `registerHook` ?

**Comment by guestisp** [comment]
What about using `/themes/default-bootstrap/manufacturer-list.tpl` ? Doing this I have to make 2 pull requests, one for the module, one for the default template in core. Right ?

**Comment by gRoussac** [comment]
yep that what i meant, mainly not to affect the default demo install. Thank you.

Regards

**Comment by gRoussac** [comment]
Don't you want to try like this 

https://github.com/PrestaShop/blocknewproducts/blob/master/views/templates/hook/blocknewproducts_home.tpl#L26 but with manufacturer-list.tpl instead. Jut to test if it can suits with a bit of css probably it should fit.

Regards

**Comment by guestisp** [comment]
We can't include it in this way because we have to change some classes and structure. This is why we created a new file.

**Comment by gRoussac** [comment]
That is sad because it is very closed to your template and you have parent id to focus.

Regards

**Comment by guestisp** [comment]
New pull request on "dev" branch: https://github.com/PrestaShop/blockmanufacturer/pull/2

**Pull request closed without merging**
